### ISSUE TITLE
Support TSLint warnings

### ISSUE THREAD

**Issue by probert94** [angelozerr/tslint-language-service#14]
It would be cool, if the language service supports both, errors and warnings.  
The IDE/Editor which is using the language service could then decide how to handle them.

**Comment by angelozerr** [comment]
This feature was already implemented. As you are Eclipse user, typescript.java didn't support severities 

It's now fixed with https://github.com/angelozerr/typescript.java/issues/170

Here a demo:

![](https://github.com/angelozerr/typescript.java/wiki/images/TslintSeverityDemo.gif)
