### ISSUE TITLE
Support for tslint4 & tslint5

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tslint-language-service#17]
@Istar-Eldritch could you update dependencies for tslint inside package.json to support 5 and 4 both.

Thanks!

**Comment by Istar-Eldritch** [comment]
Do we know if using the version 5 would imply some breaking changes?

**Comment by angelozerr** [comment]
I have changed a little code to support tslint 4 & 5 both and it works with tslint 5.

When you install tslint-language-service and tslint5 is already installed, there is a warn with peer dependencies. It should be cool to update package.json
