### ISSUE TITLE
Pass severity through to get to vscode

### ISSUE THREAD

**Issue by abierbaum** [angelozerr/tslint-language-service#22]
I have setup my tslint.json with a defaultSeverity of "warning".  But when a tslint problem shows up in the compiler output and/or comes through the vscode it shows up as an error.  Is this a limitation of the language service plugin or just something that isn't supported by typescript?

**Comment by angelozerr** [comment]
tslint-language-service consumes tslint, so the first thing to test is to execute tslint with command to check you have the same result than with VSCode.

In the [tslint doc](https://github.com/palantir/tslint/blob/master/docs/usage/configuration/index.md) you can read:

`defaultSeverity?: "error" | "warning" | "off": The severity level used when a rule specifies a default warning level. If undefined, "error" is used. This value is not inherited and is only applied to rules in this file.`

Perhaps the rule which caues `error` severity is not declared in your `tslint.json`? It seems that it's the same issue than https://github.com/Microsoft/vscode-tslint/issues/193
