### ISSUE TITLE
Unmet peerdep warning

### ISSUE THREAD

**Issue by mhartington** [angelozerr/tslint-language-service#23]
Hi there! I was attempting to use this plugin with TS 2.3.0 but got a `UNMET PEER DEPENDENCY` error.

```
├── tslint-language-service@0.9.2
└── UNMET PEER DEPENDENCY typescript@2.3.0

npm WARN tslint-language-service@0.9.2 requires a peer of typescript@2.2.x but none was installed.
```

Since TS 2.3.0 is out now, would it be possible to bump the peerDep for typescript? 

https://github.com/angelozerr/tslint-language-service/blob/master/package.json#L26

Things still install correctly, but it would be nice to not get a warning, which could scare people off. 

Either way, this plugin is great, and works perfectly with my typescript service for neovim. Thanks!

**Comment by angelozerr** [comment]
> Since TS 2.3.0 is out now, would it be possible to bump the peerDep for typescript?

We are fixing this issue in https://github.com/angelozerr/tslint-language-service/pull/24

> Either way, this plugin is great, and works perfectly with my typescript service for neovim. Thanks!

Glad this plugin is helpful for you!

**Comment by mhartington** [comment]
Ah! I should have look harder 😄 

I'll close this since there's a PR.

**Comment by angelozerr** [comment]
@mhartington please reinstall 0.9.3, it should fix your issue.

**Comment by mhartington** [comment]
Looks good! Thanks!
