### ISSUE TITLE
Add a prepublish script to ensure the code is compiled before published to npm

### ISSUE THREAD

**Issue by egamma** [angelozerr/tslint-language-service#31]
@angelozerr to avoid that something like in issue #28 happens again, please add a prepublish script in package.json that compiles the TypeScript code.

```json
	"scripts": {
		"prepublish": "tsc",
	        ....
	},
```

**Comment by egamma** [comment]
I have a PR that does this and more.

**Comment by angelozerr** [comment]
Thanks @egamma for your suggestion, I have just updated your code to use local tsc .
