### ISSUE TITLE
Some rules not working with VSCode? (e.g., semicolon)

### ISSUE THREAD

**Issue by victornoel** [angelozerr/tslint-language-service#42]
Hi,

I have setup tslint-language-service properly in vscode, and I can see errors as expected but for some rules, it just doesn't seem to work…

For example, the `semicolon` rule is never triggered.

I'm not sure how to provide more details on this issue, if you know how I can gather more data, I can do it :)

**Comment by angelozerr** [comment]
The best mean is to share a simple project which causes your problem.

**Comment by victornoel** [comment]
@angelozerr here it is:
[bug-tslint-language-service.zip](https://github.com/angelozerr/tslint-language-service/files/1057402/bug-tslint-language-service.zip)

Simply:
 - run yarn once in it (or npm, but with yarn you will get the exact same dependencies as I did).
 - open the folder with vscode.
 - force the use of the local typescript version (which should be 2.3.4)
 - open the file `src/app/app.components.ts`.
 - add a trailing whitespace to line 9: an error is shown.
 - remove the semicolon of line 9: no error is shown.

**Comment by victornoel** [comment]
Hm, apparently it seems that even with tslint alone it does not work… there is something fishy, sorry for the noise :)
