### ISSUE TITLE
configFile is broken 

### ISSUE THREAD

**Issue by krzkaczor** [angelozerr/tslint-language-service#55]
First of all, I want to say thank you for this awesome plugin.

I noticed that `configFile` is broken for me because it assumes [relative path to CWD](https://github.com/palantir/tslint/blob/master/src/configuration.ts#L128) which often is not a project root (you can ran vsc from terminal on different project but all windows share CWD). 
You can't really use absolute paths either because they would be different for every machine.

I have already patched version running locally (man, debugging `ts language services` is crazy :D) it always uses a relative path from project root. PR incoming in a sec.

**Comment by andyrooger** [comment]
Perfect timing. Thanks @krzkaczor.

@angelozerr Do you know how long this would take to make it into npm?

**Comment by angelozerr** [comment]
@andyrooger I will try to do that this week.

**Comment by angelozerr** [comment]
@andyrooger I have published 0.9.8. Thanks @krzkaczor !
