### ISSUE TITLE
Typo: "suppress", not "supres" (two 'p's)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [angelozerr/tslint-language-service#57]

**Comment by angelozerr** [comment]
Where is there this typo? Can we have a PR?

**Comment by angelozerr** [comment]
I close this issuse since I think it's an error coming from a tslint rule. We don't use 'supres' in our code.

**Comment by JoshuaKGoldberg** [comment]
I... honestly have no idea what the context was here. Probably the wrong repository.

**Comment by JoshuaKGoldberg** [comment]
Oh! Found it. @angelozerr 

`supressWhileTypeErrorsPresent` - should be `suppressWhileTypeErrorsPresent`. Incorrect spelling à la ["referer"](https://en.wikipedia.org/wiki/HTTP_referer#Etymology).

**Comment by angelozerr** [comment]
Thanks @JoshuaKGoldberg ! We must fix it. Can we have a PR please?

**Comment by JoshuaKGoldberg** [comment]
I'd be happy to. Since this is a breaking change, how do you want to approach versioning?

Proposal: bump the version to `0.10` and allow both flags, with a `console.warn` on the old one. When you hit `1.0`, remove the old one?

**Comment by angelozerr** [comment]
Yes you are right. @egamma what do you think about that?
