### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by egamma** [angelozerr/tslint-language-service#6]
I understand that this is work in progress, but here is some initial feedback:

- The tslint-language-service currently has tslint as a dependency, should this be a peer dependency? This enables to update tslint independent of the tslint-language-service. This similar to tslint itself, it also has typescript as a peer dependency only.
- I haven't seen any support for settings/options for tslint like the `tslint.json` file location (`--configFile`) or the location of additional rules (`--rulesDirectory`). I assume that such settings can also be done inside the tsconfig.json?
- Support for code fixes is work in progress, but the implementation provides custom code fixes for `no-var-keyword`, `no-trailing-whitespace` the tslint rules already provide a fix for these rules and the custom code fixes should not be needed.

**Comment by angelozerr** [comment]
Thank a lot @egamma !

> The tslint-language-service currently has tslint as a dependency, should this be a peer dependency? 

Yes sure, I will update package.json 

> I haven't seen any support for settings/options for tslint like the tslint.json file location (--configFile) 

For the moment it search tslint.json in your project root.

> the location of additional rules (--rulesDirectory). I assume that such settings can also be done inside the tsconfig.json?

I tell me if I should support that since tslint.json can declare rulesDirectory, no? Perhaps vscode-tslint does that to support any tslint version?

> Support for code fixes is work in progress, but the implementation provides custom code fixes for no-var-keyword, no-trailing-whitespace the tslint rules already provide a fix for these rules and the custom code fixes should not be needed.

Yes sure.

**Comment by egamma** [comment]
>I tell me if I should support that since tslint.json can declare rulesDirectory, no? Perhaps vscode-tslint does that to support any tslint version?

I agree that defining the `rulesDirectory` inside the tslint.json is the preferred way to do it. I cannot remember if this was always supported by tslint. vscode-tslint uses the principle to expose the tslint [command line options](https://github.com/palantir/tslint#cli-1) that make sense as user configurable settings. 

There are other settings that vscode-tslint supports based on user requests so they should supported unless there is a reason for not doing it. Please see for the [supported options](https://github.com/Microsoft/vscode-tslint/blob/master/tslint/README.md#configuration-options).

**Comment by angelozerr** [comment]
@egamma do you think we should expose those settings?

**Comment by egamma** [comment]
@angelozerr yes I think we should add support for these settings to the (to be created) backlog.

**Comment by angelozerr** [comment]
@egamma I close this issue since you have created https://github.com/angelozerr/tslint-language-service/issues/32 Please reopen it if you think we should reopen it.
