### ISSUE TITLE
Deploy the plugin as a visual studio code extension

### ISSUE THREAD

**Issue by movedoa** [angelozerr/tslint-language-service#61]
As far as i understand, this should now be possible with vsc 1.20.
See https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributestypescriptserverplugins

...or should this be an issue for vscode-tslint to include this plugin in the extension?

**Comment by movedoa** [comment]
@angelozerr Any comment?

**Comment by matheo** [comment]
It works with the TSLint (vnext) `eg2.ts-tslint` extension
using VSCode's typescript version, perhaps it doesn't support `autoFixOnSave` @angelozerr?

That is the better feature of `eg2.tslint` for my daily basis
