### ISSUE TITLE
no-floating-promises rule always throws error

### ISSUE THREAD

**Issue by uloco** [angelozerr/tslint-language-service#62]
The `no-floating-promises` rule should only throw an error, when promises aren't handled correctly. It checks for a `.then()` or `.catch()` block, so we can make sure, they do not _float_ around.
https://palantir.github.io/tslint/rules/no-floating-promises/

At the moment, I always get an error,  no matter what.

![screen shot 2018-02-21 at 09 45 20](https://user-images.githubusercontent.com/8818340/36470686-0f9f4358-16ec-11e8-832e-06c1bc09478e.png)

**Comment by angelozerr** [comment]
I think it's an issue for tslint, no?

**Comment by uloco** [comment]
I don't get the error in tslint, when running on command line.
Let me look into this, to get sure, I am using the same versions...

**Comment by uloco** [comment]
I had a version mismatch and was using a more updated version of tslint globally. Thanks for your hint, totally overlooked that. :)
