### ISSUE TITLE
tslint language service must return a function of create to support TypeScript 2.2.1

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tslint-language-service#7]
Today tslint language service works only with https://github.com/angelozerr/tsserver-plugins and with TypeScript 2.2.1 directly. 

It's because of the line https://github.com/Microsoft/TypeScript/blob/v2.2.1/src/server/project.ts#L906

```
const pluginModule = pluginModuleFactory({ typescript: ts });
this.languageService = pluginModule.create(info);
```

Today the tslint language service returns a create function although it should return a function (pluginModule ) which returns a create function.

**Comment by Istar-Eldritch** [comment]
@angelozerr I think you can close this.

**Comment by angelozerr** [comment]
Yes sure. Thanks @Istar-Eldritch for your PR!
