### ISSUE TITLE
Better labeling for issues / list of high pri tasks?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [angelozerr/tslint-language-service#88]
@angelozerr / @egamma I'm _very_ motivated to get this thing to a usable state. How can I as a prospective contributor help out? Is there a list of `good first issue` issues?

If you could label issues as `good first issue` / `high priority` / `bug` / `blocked` / etc., that'd be very helpful! 😊

**Comment by egamma** [comment]
@JoshuaKGoldberg the current implementation of the tslint-language-service is based on code from the vscode-tslint extension. Unfortunately the two code streams have evolved independently and this is now difficult to maintain. We have therefore decided to start fresh and have some initial code that we will publish soon. Looking forward to your contributions in the fresh code base.


//CC @mjbvz

**Comment by csvn** [comment]
I’m very interested in this new project @egamma. Where can we find out when it’s made public? Will you notify in this repo?

**Comment by egamma** [comment]
@csvn we will definitely notify this repo when the new repository becomes public // CC @mjbvz

**Comment by JoshuaKGoldberg** [comment]
@egamma / @mjbvz do you have a rough ball park of time frame? As in, weeks or months?

Context: the lack of typed rule support is a real pain with TSLint + VS Code. If it's months before you're planning on releasing, it'd be more efficient for us to work off of this repository / a fork of it in the meantime to get the very basic features than to wait.

**Comment by mjbvz** [comment]
We're aiming to get a preview release out this month

**Comment by mjbvz** [comment]
Here's the repo with the forked plugin: https://github.com/Microsoft/typescript-tslint-plugin

And the vscode extension that contributes this plugin: https://github.com/Microsoft/vscode-typescript-tslint-plugin The extension should be published to the marketplace sometime this week

**Comment by lumaxis** [comment]
Fantastic news, thanks @mjbvz!

**Comment by JoshuaKGoldberg** [comment]
Hooray!
