### ISSUE TITLE
Create npm package

### ISSUE THREAD

**Issue by Istar-Eldritch** [angelozerr/tslint-language-service#9]
Using `npm link` is only a good solution during development. I would like to include this as a dev dependency in my `package.json` so everybody in the team uses the lint by default.

It would be nice to add the project to a CI and configure it to do automatic deployments when a new tag is added.

**Comment by Istar-Eldritch** [comment]
@angelozerr let me know if you need help with this stuff.

**Comment by angelozerr** [comment]
> let me know if you need help with this stuff.

Yes please, I don't know this feature -(
